#!/bin/bash

read -p "Please enter the GitHub repository link: " link
read -p "You also need to provide you GitHub Authorization token in order to send API requests: " token
#Retrieve repository and user variables from the link

user=$(echo $link | awk -F/ '$0=$4')
repo=$(echo $link | awk -F/ '$0=$5')
justline=$(echo "--------------------------------------------------------------------------------------------------------------")

i=0
#checking any openned PR
 
open_pr=$(curl -s -H "Authorization: token $token" https://api.github.com/repos/$user/$repo/pulls?state=open |jq '.[0].state') 
if [[ "$open_pr" == null ]]; then
	echo $justline
	echo "There is no openned Pull Requests"
	echo $justline
else
	echo $justline
	echo "We have found openned Pull Requests"
	echo "Below are the contributors who have created more than 1 PR:"
	echo $justline
fi

contributors=""
contributors_labels=""

while [ $(curl -s -H "Authorization: token $token" https://api.github.com/repos/$user/$repo/pulls?state=all |jq --argjson n "$i" '.[$n].state') != null ]; do

#	echo -e $(curl -s https://api.github.com/repos/$user/$repo/pulls?state=open |jq --argjson n "$i" '.[$n].user.login') " created Pull request"$'\n'
	requestor=$(curl -s -H "Authorization: token $token" https://api.github.com/repos/$user/$repo/pulls?state=all |jq --argjson n "$i" '.[$n].user.login')
	if [[ $(curl -s -H "Authorization: token $token" https://api.github.com/repos/$user/$repo/pulls?state=all |jq --argjson n "$i" '.[$n].labels' |jq '.[0].id') -ne null ]]; then
		contributors_labels="${contributors_labels}${requestor}\n"
	fi

	i=$(($i + 1))
	contributors="${contributors}${requestor}\n"
#	echo $i
done

echo -e $contributors |awk 'NF'| sort | uniq -d
echo $justline
if [[ -n $(echo $contributors_labels) ]]; then
	echo ""
	echo "Here is the contributors who created PR with labels in format:"
	echo "%Number of PRs with Labels% and %Contributor%"
	echo $justline 
	echo -e $contributors_labels |awk 'NF' | sort |uniq -c
	echo $justline
fi
#echo -e $result

